
title: Flying Data Analyst
theme: jekyll-theme-modernist
description: timesavers on linux, python, d3 and data science.

encoding: UTF-8
repository: wuliong/blog
show_view_on_github: false
show_downloads: false
show_theme_author: false



plugins:
  - "jekyll-github-metadata"



