
title: Flying Data Analyst
theme: jekyll-theme-modernist
description: tips & tricks on linux, python, d3, nlp, ...

encoding: UTF-8
repository: wuliong/blog
show_view_on_github: false
show_downloads: false
show_theme_author: false



plugins:
  - "jekyll-github-metadata"



