title: Flying Data Analyst
theme: jekyll-theme-modernist
description: timesavers on linux, python, d3 and data science.
author: Linghong Hu
timezone: Asia/Shanghai
encoding: UTF-8
repository: wuliong/blog
github: [metadata]
permalink: /:slug



plugins:
  - jekyll-github-metadata


text:
  index:
    coming_soon: 'Coming soon...'