title: Flying Data Analyst
theme: jekyll-theme-modernist
description: timesavers on linux, python, d3 and data science.
author: Linghong Hu
timezone: Asia/Shanghai
encoding: UTF-8
repository: wuliong/blog
permalink: /:slug
baseurl: "/blog"

markdown: kramdown
highlighter: rouge
text_coming_soon: 'Coming soon...' 

plugins:
  - jekyll-github-metadata
